// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
using Postman.DataObjects;

[TestFixture]
public class BillingOrderPage {
  private IWebDriver driver;

    public BillingOrderPage(IWebDriver driver)
    {
        this.driver = driver;
    }
  
  [Test]
  public void SubmitBillingOrder(BillingOrder order) {
    driver.Navigate().GoToUrl("https://qaauto.co.nz/billing-order-form/");
    driver.Manage().Window.Size = new System.Drawing.Size(1440, 900);
    driver.FindElement(By.Id("wpforms-locked-24-field_form_locker_password")).Click();
    driver.FindElement(By.Id("wpforms-locked-24-field_form_locker_password")).SendKeys("Testing");
    driver.FindElement(By.Id("wpforms-submit-locked-24")).Click();
    driver.FindElement(By.Id("wpforms-24-field_0")).SendKeys(order.firstName);
    driver.FindElement(By.Id("wpforms-24-field_0-last")).SendKeys(order.lastName);
    driver.FindElement(By.Id("wpforms-24-field_1")).SendKeys(order.email);
    driver.FindElement(By.Id("wpforms-24-field_3")).SendKeys(order.addressLine1);
    driver.FindElement(By.Id("wpforms-24-field_3-address2")).SendKeys(order.addressLine2);
    driver.FindElement(By.Id("wpforms-24-field_3-city")).SendKeys(order.city);
  
    {
      var dropdown = driver.FindElement(By.Id("wpforms-24-field_3-state"));
      dropdown.FindElement(By.XPath("//option[. = 'California']")).Click();
    }
 
    driver.FindElement(By.Id("wpforms-24-field_6")).SendKeys("testing");
    var elements = driver.FindElements(By.CssSelector("#wpforms-confirmation-24 > p"));
    //Assert.True(elements.Count > 0);
    //Assert.That(driver.FindElement(By.CssSelector("#wpforms-confirmation-24 > p")).Text, Is.EqualTo("Thanks for contacting us! We will be in touch with you shortly."));
     driver.FindElement(By.Id("wpforms-form-page-page")).Click();

    }

}
